name: Dependabot

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Dependabot Go
        uses: dependabot/dependabot-core@0.159.x
        with:
          directory: '/'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          update: true
          ignore: |
            docker/**
      - name: Dependabot Docker
        uses: dependabot/dependabot-core@0.159.x
        with:
          directory: '/'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          update: true
          ignore: |
            go.mod,go.sum
            !Dockerfile
